seed: 0
out_file: ./result/cifar10/CIFAR10_no_bl

dataset:
  name: cifar10
  root: ../data/cifar10
  aug: False
  batch_size: 128
  test_workers: 1
  workers: 4

model:
  name: PreResNet
  kwargs:
    depth: 44
    num_classes: 10

train:
  opt:
    name: SGD
    kwargs:
      lr: 0.1
      momentum: 0.9
      nesterov: True
      # weight_decay: 0.0001
    schedule:
      name: MultiStepLR
      kwargs:
        milestones: [80, 120]
        gamma: 0.1

  loss_type: basic
  save_tag: True
  save_epoch: 10
  save_path: ./cifar10/no_bl
  exp_info: cifar10_no_bl
  epoch: 160
  log_step: 20
