seed: 0
out_file: ./result/mnist/MNIST_no_bl

dataset:
  name: mnist
  root: ../data
  batch_size: 100
  test_workers: 1
  workers: 4

model:
  name: MLP
  kwargs:
    channels: [784, 1024, 1024, 10]

train:
  opt:
    name: Adam
    kwargs:
      lr: 0.001
      betas: [0.5, 0.999]
      # weight_decay: 0.00001
    schedule:
      name: StepLR
      kwargs:
        step_size: 2
        gamma: 0.97

  loss_type: basic
  save_tag: True
  save_epoch: 20
  save_path: ./mnist/no_bl
  exp_info: mnist_no_bl
  epoch: 200
  log_step: 50
